# Generated by Django 3.0 on 2020-12-07 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201207_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата публикации'),
        ),
    ]
