# Generated by Django 3.0 on 2020-12-11 06:49

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201207_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Школа')),
                ('sub_domen', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Домен')),
                ('school_logo_1', models.FileField(blank=True, null=True, upload_to='logo', verbose_name='Лого 250x64')),
                ('school_logo_2', models.FileField(blank=True, null=True, upload_to=app.models.content_file_name, verbose_name='Лого 16x16')),
            ],
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='school_logo_1',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='school_logo_2',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='sub_domen',
        ),
        migrations.AddField(
            model_name='appuser',
            name='school_id',
            field=models.ForeignKey(blank=True, help_text='Школа', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.School'),
        ),
    ]
