# Generated by Django 3.0 on 2020-12-11 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201211_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='creator_id',
            field=models.ForeignKey(blank=True, help_text='Создатель школы', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
