# Generated by Django 3.0 on 2020-12-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='school_name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='sub_domen',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Домен'),
        ),
    ]
