# Generated by Django 3.1.5 on 2021-01-26 06:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('short_desc', models.TextField(blank=True, max_length=200, null=True, verbose_name='Короткое описание')),
                ('pub_date', models.DateField(blank=True, default=datetime.date.today, verbose_name='Дата публикации')),
                ('course_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество курсов')),
                ('duration', models.IntegerField(blank=True, default=0, help_text='в минутах', null=True, verbose_name='Длителность')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='knowledgebase', verbose_name='Файлы')),
                ('pub_date', models.DateField(blank=True, default=datetime.date.today, verbose_name='Дата публикации')),
                ('course_id', models.ForeignKey(blank=True, help_text='курс', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.course')),
                ('lesson_id', models.ForeignKey(blank=True, help_text='урок', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('desc', models.TextField(blank=True, max_length=200, null=True, verbose_name='Короткое описание')),
                ('files', models.FileField(blank=True, null=True, upload_to='lessons', verbose_name='Содержание ДЗ')),
                ('pub_date', models.DateField(blank=True, default=datetime.date.today, verbose_name='Дата публикации')),
                ('course_id', models.ForeignKey(blank=True, help_text='курс', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.course')),
                ('lesson_id', models.ForeignKey(blank=True, help_text='урок', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.lesson')),
                ('student_id', models.ForeignKey(blank=True, help_text='Учитель курса', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='vector_id',
            field=models.ForeignKey(blank=True, help_text='Направление', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.vector'),
        ),
    ]
