# Generated by Django 3.0 on 2020-11-26 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201126_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='birth_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Birth date'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='fathername',
            field=models.CharField(blank=True, max_length=150, verbose_name='father name'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='gender',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Male'), (2, 'Female')], default=0),
        ),
        migrations.AddField(
            model_name='appuser',
            name='phone',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
