# Generated by Django 3.1.5 on 2021-01-29 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210129_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Дата публикации'),
        ),
    ]
