# Generated by Django 3.0 on 2021-02-08 07:20

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_lesson_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='change_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата изменении'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='files',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='hw'), upload_to='', verbose_name='Содержание ДЗ'),
        ),
    ]
