# Generated by Django 3.0 on 2020-11-26 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201126_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='card',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='client_activity',
            field=models.DateTimeField(null=True, verbose_name='Активность клиента'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='country',
            field=models.CharField(default='Kazakhstan', max_length=20),
        ),
        migrations.AddField(
            model_name='appuser',
            name='lead_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appuser',
            name='position',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='subdivison',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
