# Generated by Django 3.1.5 on 2021-01-30 07:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='course',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='student_id',
            field=models.ForeignKey(blank=True, help_text='Ученик курса', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Course_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Начало даты')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Конец даты')),
                ('activity', models.DateTimeField(blank=True, null=True, verbose_name='Активность клиента')),
                ('course_id', models.ForeignKey(blank=True, help_text='курс', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.course')),
                ('student_id', models.ForeignKey(blank=True, help_text='Ученик курса', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
