# Generated by Django 3.0 on 2021-02-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210208_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='change_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменении'),
        ),
    ]
