# Generated by Django 3.0 on 2020-12-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201203_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='school_logo_1',
            field=models.FileField(blank=True, null=True, upload_to='logo', verbose_name='Лого 250x64'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='school_logo_2',
            field=models.FileField(blank=True, null=True, upload_to='logo', verbose_name='Лого 16x16'),
        ),
    ]
