# Generated by Django 3.1.5 on 2021-02-01 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210130_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='vector',
            name='creator_id',
            field=models.ForeignKey(blank=True, help_text='Создатель курса', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
