# Generated by Django 3.0 on 2020-12-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201204_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='sub_domen',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Домен'),
        ),
    ]
