# Generated by Django 3.0 on 2020-12-01 06:54

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'permissions': [('can_add_comment', 'Can add comments'), ('can_edit_user_data', 'Can edit user data')]},
        ),
        migrations.AlterField(
            model_name='appuser',
            name='birth_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата рождение'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='card',
            field=models.CharField(max_length=16, null=True, verbose_name='Банковская карта'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='country',
            field=models.CharField(default='Kazakhstan', max_length=20, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='fathername',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='gender',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Male'), (2, 'Female')], default=0, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='lead_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Активность лида'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=models.CharField(max_length=15, null=True, verbose_name='Сотовый'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='position',
            field=models.CharField(max_length=20, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='subdivison',
            field=models.CharField(max_length=20, null=True, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
    ]
