# Generated by Django 3.0 on 2021-02-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210208_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='checked',
        ),
        migrations.AddField(
            model_name='homework',
            name='checked',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Проверено?'),
        ),
    ]
