# Generated by Django 3.0 on 2020-12-02 04:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201201_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Дата рождение'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='card',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Банковская карта'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='country',
            field=models.CharField(default='Kazakhstan', max_length=20, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='fathername',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='lead_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Активность лида'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Сотовый'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='position',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='subdivison',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cost',
            field=models.IntegerField(default=0, help_text='в тенге', verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_programm',
            field=models.CharField(max_length=30, verbose_name='Программа курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='creator_id',
            field=models.ForeignKey(blank=True, help_text='Создатель курса', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=0, help_text='в минутах', verbose_name='Длителность'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(verbose_name='Конец даты'),
        ),
        migrations.AlterField(
            model_name='course',
            name='full_desc',
            field=models.TextField(max_length=500, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='poster',
            field=models.TextField(max_length=1000, verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='course',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_desc',
            field=models.TextField(max_length=200, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Начало даты'),
        ),
    ]
