# Generated by Django 3.0 on 2020-12-04 06:30

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201204_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'permissions': []},
        ),
        migrations.AlterField(
            model_name='appuser',
            name='client_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Активность клиента'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='school_logo_2',
            field=models.FileField(blank=True, null=True, upload_to=app.models.content_file_name, verbose_name='Лого 16x16'),
        ),
    ]
