# Generated by Django 3.1.5 on 2021-02-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_vector_creator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='title',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Название'),
        ),
    ]
