# Generated by Django 3.0 on 2021-02-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210217_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Название шаблона'),
        ),
    ]
