# Generated by Django 3.0 on 2020-12-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201204_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
