# Generated by Django 3.0 on 2021-02-26 05:38

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210223_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise_list',
            name='course_id',
        ),
        migrations.AddField(
            model_name='exercise_list',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=app.models.content_file_name_ex_list, verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=app.models.content_file_name_ex, verbose_name='Содержание ДЗ'),
        ),
    ]
