# Generated by Django 3.0 on 2021-02-26 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210226_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise_list',
            name='ex_id',
        ),
        migrations.AddField(
            model_name='exercise',
            name='ex_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Exercise_list'),
        ),
    ]
