# Generated by Django 3.0 on 2020-12-07 12:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201207_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lesson_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество уроков'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('short_desc', models.TextField(blank=True, max_length=200, null=True, verbose_name='Короткое описание')),
                ('full_desc', models.TextField(blank=True, max_length=500, null=True, verbose_name='Полное описание')),
                ('duration', models.IntegerField(blank=True, default=0, help_text='в минутах', null=True, verbose_name='Длителность')),
                ('files', models.FileField(blank=True, null=True, upload_to='lessons', verbose_name='Содержание урока')),
                ('pub_date', models.DateTimeField(default=datetime.date.today, verbose_name='Дата публикации')),
                ('course_id', models.ForeignKey(blank=True, help_text='курс', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Course')),
                ('teacher_id', models.ForeignKey(blank=True, help_text='Учитель курса', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
