# Generated by Django 3.0 on 2021-02-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210226_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_list',
            name='title',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Название задании'),
        ),
    ]
